/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsDiffOptions {
  /** Numerical comparison tolerance */
  epsilon?: number
  /** Key to use for array element identification */
  arrayIdKey?: string
  /** Regex pattern for keys to ignore */
  ignoreKeysRegex?: string
  /** Only show differences in paths containing this string */
  pathFilter?: string
  /** Output format */
  outputFormat?: string
  /** Ignore whitespace differences */
  ignoreWhitespace?: boolean
  /** Ignore case differences */
  ignoreCase?: boolean
  /** Report only whether files differ */
  briefMode?: boolean
  /** Suppress normal output; return only exit status */
  quietMode?: boolean
}
export interface JsDiffResult {
  /** Type of difference ('Added', 'Removed', 'Modified', 'TypeChanged') */
  diffType: string
  /** Path to the changed element */
  path: string
  /** Old value (for Modified/TypeChanged) */
  oldValue?: any
  /** New value (for Modified/TypeChanged/Added) */
  newValue?: any
  /** Value (for Removed) */
  value?: any
}
/**
 * Unified diff function for JavaScript/Node.js
 *
 * Compare two JavaScript objects or values and return differences.
 *
 * # Arguments
 *
 * * `old` - The old value (JavaScript object, array, or primitive)
 * * `new` - The new value (JavaScript object, array, or primitive)
 * * `options` - Optional configuration object
 *
 * # Returns
 *
 * Array of difference objects
 *
 * # Example
 *
 * ```javascript
 * const { diff } = require('diffx-js');
 *
 * const old = { a: 1, b: 2 };
 * const new = { a: 1, b: 3 };
 * const result = diff(old, new);
 * console.log(result); // [{ type: 'Modified', path: 'b', oldValue: 2, newValue: 3 }]
 * ```
 */
export declare function diff(old: any, new: any, options?: JsDiffOptions | undefined | null): Array<JsDiffResult>
/**
 * Parse JSON string to JavaScript object
 *
 * # Arguments
 *
 * * `content` - JSON string to parse
 *
 * # Returns
 *
 * Parsed JavaScript object
 */
export declare function parseJson(content: string): any
/**
 * Parse CSV string to JavaScript array of objects
 *
 * # Arguments
 *
 * * `content` - CSV string to parse
 *
 * # Returns
 *
 * Array of JavaScript objects representing CSV rows
 */
export declare function parseCsv(content: string): any
/**
 * Parse YAML string to JavaScript object
 *
 * # Arguments
 *
 * * `content` - YAML string to parse
 *
 * # Returns
 *
 * Parsed JavaScript object
 */
export declare function parseYaml(content: string): any
/**
 * Parse TOML string to JavaScript object
 *
 * # Arguments
 *
 * * `content` - TOML string to parse
 *
 * # Returns
 *
 * Parsed JavaScript object
 */
export declare function parseToml(content: string): any
/**
 * Parse INI string to JavaScript object
 *
 * # Arguments
 *
 * * `content` - INI string to parse
 *
 * # Returns
 *
 * Parsed JavaScript object
 */
export declare function parseIni(content: string): any
/**
 * Parse XML string to JavaScript object
 *
 * # Arguments
 *
 * * `content` - XML string to parse
 *
 * # Returns
 *
 * Parsed JavaScript object
 */
export declare function parseXml(content: string): any
/**
 * Format diff results as string
 *
 * # Arguments
 *
 * * `results` - Array of diff results
 * * `format` - Output format ("diffx", "json", "yaml")
 *
 * # Returns
 *
 * Formatted string output
 */
export declare function formatOutput(results: Array<JsDiffResult>, format: string): string
